version: '3'
services:
  nodejs_app:
    build: .
    ports:
      - "3000:3000" # Замените на порт вашего Node.js приложения
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Замените на путь к вашему Nginx конфигу
    ports:
      - "80:80"
      - "443:443"
  certbot:
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email dastan@zholdas.icu --agree-tos -d api.qrder.su
    volumes:
      - ./certbot-data:/var/www/certbot
    depends_on:
      - nginx
