version: '3'
services:
  nodejs_app:
    build: .
    ports:
      - "4001:4001"
    networks:
      - app_network

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_network

  certbot:
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email dastan@zholdas.icu --agree-tos -d api.qrder.su
    volumes:
      - ./certbot-data:/var/www/certbot
    depends_on:
      - nginx
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
