version: '3'
services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001" # Проксирование порта Node.js

  nginx:
    image: nginx
    ports:
      - "80:80"   # Порт для HTTP
      - "443:443" # Порт для HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt # Монтирование папки Let's Encrypt

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email dastan@zholdas.icu --agree-tos -d ${DOMAIN}
